<?php

declare(strict_types=1);

namespace App\Domain\Connector;

use coyshdigital\managerprotocol\Keys;
use RuntimeException;

/**
 * The platform's own Ed25519 identity.
 *
 * Used to sign responses that carry commands or security-sensitive configuration, so a connector
 * can tell an instruction from this platform apart from one injected by whatever sits between
 * them.
 *
 * Generated by `manager:keys:generate` during setup. Supplying it through the environment instead
 * is supported so that immutable deployments never have to write to disk.
 */
final class PlatformKeypair
{
    public function publicKey(): string
    {
        return $this->require('public_key');
    }

    public function secretKey(): string
    {
        return $this->require('secret_key');
    }

    /**
     * Whether a usable keypair is configured.
     *
     * Checked by `manager:doctor`, because a platform that cannot sign its own responses will only
     * discover the fact the first time a connector needs one.
     */
    public function isConfigured(): bool
    {
        $public = config('manager.signing.public_key');
        $secret = config('manager.signing.secret_key');

        return is_string($public)
            && is_string($secret)
            && $public !== ''
            && $secret !== ''
            && Keys::isValidPublicKey($public);
    }

    private function require(string $key): string
    {
        $value = config("manager.signing.{$key}");

        if (! is_string($value) || $value === '') {
            throw new RuntimeException(
                "The platform signing {$key} is not configured. Run `php artisan manager:keys:generate`."
            );
        }

        return $value;
    }
}
