<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Registered passkeys.
 *
 * One row per credential, not per account: somebody with a laptop and a phone has two, and removing
 * one must not disarm the other.
 *
 * `credential` holds the serialised WebAuthn credential record — public key, transports, and the
 * signature counter that is rewritten on every use to detect a cloned authenticator. There is no
 * secret in here: the private half never leaves the device, which is the whole point of a passkey and
 * the reason this table is far less dangerous to hold than a table of TOTP seeds.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('passkeys', function (Blueprint $table): void {
            $table->id();

            // Cascading, so removing an account takes its credentials with it. A credential outliving
            // its owner would be an orphaned row that still matches a real authenticator.
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();

            // What the operator called it, shown when choosing which one to remove.
            $table->string('name');

            // Unique across the table rather than per user. A credential ID is generated by the
            // authenticator and is the lookup key during an assertion, so two accounts holding the
            // same one would make that lookup ambiguous.
            $table->string('credential_id')->unique();

            $table->json('credential');
            $table->timestamp('last_used_at')->nullable();
            $table->timestamps();

            $table->index('user_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('passkeys');
    }
};
