<?php

declare(strict_types=1);

use coyshdigital\managerprotocol\Protocol;

return [

    /*
    |---------------------------------------------------------------------------------------------
    | Pairing
    |---------------------------------------------------------------------------------------------
    |
    | An enrolment code is a bearer secret until it is consumed, so it is short-lived by design.
    | Attempt limits exist because rate limiting, not hashing cost, is what stops guessing: the
    | code carries 256 bits of entropy and there is no dictionary to slow an attacker down to.
    |
    */

    'enrolment' => [
        'ttl' => (int) env('MANAGER_ENROLMENT_TTL', 900),
        'max_attempts_per_ip' => (int) env('MANAGER_ENROLMENT_MAX_ATTEMPTS_IP', 10),
        'max_attempts_per_site' => (int) env('MANAGER_ENROLMENT_MAX_ATTEMPTS_SITE', 5),
        'decay_seconds' => (int) env('MANAGER_ENROLMENT_DECAY', 900),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Connector requests
    |---------------------------------------------------------------------------------------------
    |
    | The timestamp tolerance and the nonce retention move together: the store has to remember a
    | nonce for at least as long as its timestamp could still be accepted, which is why the TTL is
    | derived rather than configured separately.
    |
    */

    'connector' => [
        'timestamp_tolerance' => (int) env('MANAGER_TIMESTAMP_TOLERANCE', Protocol::DEFAULT_TIMESTAMP_TOLERANCE),
        'max_payload_bytes' => (int) env('MANAGER_MAX_PAYLOAD_BYTES', Protocol::MAX_PAYLOAD_BYTES),
        'rate_limit_per_site' => (int) env('MANAGER_RATE_LIMIT_SITE', 60),
        'rate_limit_per_ip' => (int) env('MANAGER_RATE_LIMIT_IP', 120),

        /*
        | Which cache store holds seen nonces. This must be a shared, atomic store: the replay
        | check relies on an atomic add, and an in-process store would let a replay through on a
        | second worker. If it is unreachable, verification rejects rather than passes.
        */
        'nonce_store' => env('MANAGER_NONCE_STORE', 'redis'),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Platform signing key
    |---------------------------------------------------------------------------------------------
    |
    | The Ed25519 keypair the platform signs responses with. Generated by `manager:keys:generate`
    | during setup and stored encrypted; the environment variables exist so an immutable
    | deployment can supply them instead.
    |
    */

    'signing' => [
        'public_key' => env('MANAGER_SIGNING_PUBLIC_KEY'),
        'secret_key' => env('MANAGER_SIGNING_SECRET_KEY'),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Backups
    |---------------------------------------------------------------------------------------------
    |
    | The encryption keypair is X25519 and separate from the Ed25519 signing pair above. Using one
    | keypair for both signing and encryption is a well-known way to weaken both, so there are two.
    |
    | A connector seals each artifact's key to the public half, which it holds from pairing. Only the
    | secret half opens it — which means, stated plainly, that whoever holds this key can read every
    | backup. That is not end-to-end encryption and the documentation does not claim it is.
    |
    | The size ceiling is a policy statement, not a buffer size. Nothing is ever held in memory: an
    | artifact larger than this is a site whose backup strategy needs a conversation.
    |
    */

    'backups' => [
        'public_key' => env('MANAGER_BACKUP_PUBLIC_KEY'),
        'secret_key' => env('MANAGER_BACKUP_SECRET_KEY'),

        'disk' => env('MANAGER_BACKUP_DISK', 'backups'),

        'max_bytes' => (int) env('MANAGER_BACKUP_MAX_BYTES', Protocol::MAX_ARTIFACT_BYTES),

        /*
         | Total bytes one organisation may hold, across every site. Unset by default, because an
         | operator who has not asked for a limit should not discover one.
         |
         | max_bytes above stops a single enormous dump; this stops forty ordinary ones. The failure
         | it prevents is the worse of the two: a volume that fills, after which every site's backups
         | fail at once, including the ones that were behaving.
         |
         | Null rather than a large number so that "no limit" stays distinguishable from "a big one".
         */
        'quota_bytes' => env('MANAGER_BACKUP_QUOTA_BYTES') === null
            ? null
            : (int) env('MANAGER_BACKUP_QUOTA_BYTES'),

        // How long a declared artifact may sit without its bytes arriving before it is written off.
        // Generous, because a large dump on a slow connection is not a failure.
        'upload_window' => (int) env('MANAGER_BACKUP_UPLOAD_WINDOW', 3600),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Site health
    |---------------------------------------------------------------------------------------------
    |
    | How a site's check-in record is read. The interval mirrors the connector's own heartbeat
    | schedule; an operator who has changed the cron across their fleet sets it here, or every site
    | reports a permanent shortfall against a cadence nobody is keeping.
    |
    | The grace multiplier is what separates "a queue was busy" from "this site has stopped". Three
    | missed beats — fifteen minutes at the default — before a gap is called an outage.
    |
    | Retention is not optional. Uptime is derived from the heartbeats table rather than stored, so it
    | grows at roughly 8,600 rows per site per month, and the runtime and sign-in reports add another
    | 1,600 between them. Only the latest of each report is ever displayed — the history is kept so
    | somebody investigating an incident can look back, not because a screen needs it — so ninety days
    | is already generous. Nothing else would ever remove any of it.
    |
    */

    'health' => [
        'heartbeat_interval' => (int) env('MANAGER_HEARTBEAT_INTERVAL', 300),
        'heartbeat_grace_multiplier' => (int) env('MANAGER_HEARTBEAT_GRACE', 3),

        // Covers heartbeats, runtime reports and sign-in reports. MANAGER_HEARTBEAT_RETENTION_DAYS
        // is still honoured: it was the documented name before the other two tables existed, and
        // silently ignoring an operator's existing setting would be the wrong way to rename one.
        'telemetry_retention_days' => (int) env(
            'MANAGER_TELEMETRY_RETENTION_DAYS',
            env('MANAGER_HEARTBEAT_RETENTION_DAYS', 90),
        ),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Account security
    |---------------------------------------------------------------------------------------------
    */

    'auth' => [
        'recent_auth_minutes' => (int) env('MANAGER_RECENT_AUTH_MINUTES', 15),
        'max_login_attempts' => (int) env('MANAGER_MAX_LOGIN_ATTEMPTS', 5),
        'login_decay_seconds' => (int) env('MANAGER_LOGIN_DECAY', 900),
        'recovery_code_count' => 10,

        /*
        | Public registration is off by default and there is no environment variable to turn it on
        | in the self-hosted edition. Accounts are created by an owner, or through the one-time
        | setup flow.
        */
        'allow_registration' => false,
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Setup
    |---------------------------------------------------------------------------------------------
    |
    | The first-run flow that creates the owner account. It disables itself permanently once an
    | owner exists — the route stops resolving rather than merely being hidden.
    |
    */

    'setup' => [
        'ttl' => (int) env('MANAGER_SETUP_TTL', 3600),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Trusted proxies
    |---------------------------------------------------------------------------------------------
    |
    | Mirrored here as well as being read in bootstrap/app.php so that `manager:doctor` can report
    | on it. Reading env() from application code would return null once the config is cached, and a
    | check that silently passes on a production install is worse than no check.
    |
    | Never "*": trusting every proxy lets any caller set X-Forwarded-For, which defeats the
    | per-network rate limits and the source addresses recorded in the audit log.
    |
    */

    'trusted_proxies' => env('MANAGER_TRUSTED_PROXIES', ''),

    /*
    |---------------------------------------------------------------------------------------------
    | Diagnostics
    |---------------------------------------------------------------------------------------------
    |
    | Optional, off by default, and never mandatory in a self-hosted deployment. Carries no site
    | content and no secrets, is visible in settings, and can be turned off again at any time.
    |
    */

    'diagnostics' => [
        'enabled' => (bool) env('MANAGER_DIAGNOSTICS_ENABLED', false),
        'endpoint' => env('MANAGER_DIAGNOSTICS_ENDPOINT'),
    ],

];
