<?php

declare(strict_types=1);

use coyshdigital\managerprotocol\Protocol;

return [

    /*
    |---------------------------------------------------------------------------------------------
    | Edition
    |---------------------------------------------------------------------------------------------
    |
    | "self-hosted" or "cloud". The same core runs both; this only selects which implementations
    | are bound for the cloud-specific contracts, and which hardening checks apply.
    |
    */

    'edition' => env('MANAGER_EDITION', 'self-hosted'),

    /*
    |---------------------------------------------------------------------------------------------
    | Pairing
    |---------------------------------------------------------------------------------------------
    |
    | An enrolment code is a bearer secret until it is consumed, so it is short-lived by design.
    | Attempt limits exist because rate limiting, not hashing cost, is what stops guessing: the
    | code carries 256 bits of entropy and there is no dictionary to slow an attacker down to.
    |
    */

    'enrolment' => [
        'ttl' => (int) env('MANAGER_ENROLMENT_TTL', 900),
        'max_attempts_per_ip' => (int) env('MANAGER_ENROLMENT_MAX_ATTEMPTS_IP', 10),
        'max_attempts_per_site' => (int) env('MANAGER_ENROLMENT_MAX_ATTEMPTS_SITE', 5),
        'decay_seconds' => (int) env('MANAGER_ENROLMENT_DECAY', 900),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Connector requests
    |---------------------------------------------------------------------------------------------
    |
    | The timestamp tolerance and the nonce retention move together: the store has to remember a
    | nonce for at least as long as its timestamp could still be accepted, which is why the TTL is
    | derived rather than configured separately.
    |
    */

    'connector' => [
        'timestamp_tolerance' => (int) env('MANAGER_TIMESTAMP_TOLERANCE', Protocol::DEFAULT_TIMESTAMP_TOLERANCE),
        'max_payload_bytes' => (int) env('MANAGER_MAX_PAYLOAD_BYTES', Protocol::MAX_PAYLOAD_BYTES),
        'rate_limit_per_site' => (int) env('MANAGER_RATE_LIMIT_SITE', 60),
        'rate_limit_per_ip' => (int) env('MANAGER_RATE_LIMIT_IP', 120),

        /*
        | Which cache store holds seen nonces. This must be a shared, atomic store: the replay
        | check relies on an atomic add, and an in-process store would let a replay through on a
        | second worker. If it is unreachable, verification rejects rather than passes.
        */
        'nonce_store' => env('MANAGER_NONCE_STORE', 'redis'),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Platform signing key
    |---------------------------------------------------------------------------------------------
    |
    | The Ed25519 keypair the platform signs responses with. Generated by `manager:keys:generate`
    | during setup and stored encrypted; the environment variables exist so an immutable
    | deployment can supply them instead.
    |
    */

    'signing' => [
        'public_key' => env('MANAGER_SIGNING_PUBLIC_KEY'),
        'secret_key' => env('MANAGER_SIGNING_SECRET_KEY'),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Account security
    |---------------------------------------------------------------------------------------------
    */

    'auth' => [
        'recent_auth_minutes' => (int) env('MANAGER_RECENT_AUTH_MINUTES', 15),
        'max_login_attempts' => (int) env('MANAGER_MAX_LOGIN_ATTEMPTS', 5),
        'login_decay_seconds' => (int) env('MANAGER_LOGIN_DECAY', 900),
        'recovery_code_count' => 10,

        /*
        | Public registration is off by default and there is no environment variable to turn it on
        | in the self-hosted edition. Accounts are created by an owner, or through the one-time
        | setup flow.
        */
        'allow_registration' => false,
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Setup
    |---------------------------------------------------------------------------------------------
    |
    | The first-run flow that creates the owner account. It disables itself permanently once an
    | owner exists — the route stops resolving rather than merely being hidden.
    |
    */

    'setup' => [
        'ttl' => (int) env('MANAGER_SETUP_TTL', 3600),
    ],

    /*
    |---------------------------------------------------------------------------------------------
    | Diagnostics
    |---------------------------------------------------------------------------------------------
    |
    | Optional, off by default, and never mandatory in a self-hosted deployment. Carries no site
    | content and no secrets, is visible in settings, and can be turned off again at any time.
    |
    */

    'diagnostics' => [
        'enabled' => (bool) env('MANAGER_DIAGNOSTICS_ENABLED', false),
        'endpoint' => env('MANAGER_DIAGNOSTICS_ENDPOINT'),
    ],

];
