<?php

declare(strict_types=1);

namespace App\Domain\Findings\Rules;

use App\Domain\Findings\Rule;
use App\Domain\Findings\RuleCategory;
use App\Domain\Findings\RuleMatch;
use App\Domain\Findings\Severity;
use App\Domain\Findings\Snapshot;
use App\Models\Site;

/**
 * A TLS certificate a browser would refuse, for a reason other than its age.
 *
 * Like {@see CertificateExpiring}, this needs no capability - it comes from the platform's own
 * observation rather than from anything the site said, and the connector could not answer it in any
 * case. TLS terminates at the edge, so PHP on the origin sees whatever a proxy put in `$_SERVER`.
 *
 * Three faults, one rule. They share a symptom - a visitor gets an interstitial and leaves - and they
 * share the fact that nothing degrades first: unlike expiry, there is no warning period during which
 * somebody could notice, because the certificate was already wrong on the day it was installed.
 *
 * They are reported as one finding rather than three because a site rarely has more than one of them,
 * and when it does they are usually the same underlying mistake seen from different angles: a
 * self-signed certificate is also untrusted, and a certificate someone generated by hand is often
 * also for the wrong name. Three findings would be three rows about one bad install.
 *
 * **Expiry is deliberately excluded**, and is left to {@see CertificateExpiring} entirely. Folding it
 * in would open two findings on the morning a certificate lapses, with different titles, different
 * thresholds and the same remedy.
 *
 * Nothing fires on a null. A site whose certificate has never been checked, one that could not be
 * reached, and one checked by a server with no certificate authorities installed all record their
 * judgements as null - and a rule that read null as false would put a high-severity finding on every
 * site in a fleet the first morning after an upgrade, each of them describing this platform rather
 * than the site it names.
 */
final class CertificateUntrusted implements Rule
{
    public function key(): string
    {
        return 'certificate_untrusted';
    }

    public function category(): string
    {
        return RuleCategory::SECURITY;
    }

    public function requiresCapability(): ?string
    {
        return null;
    }

    public function evaluate(Snapshot $snapshot): ?RuleMatch
    {
        $site = $snapshot->site;

        if ($site->certificate_checked_at === null) {
            return null;
        }

        // The wrong name first. It is the one an operator can least afford to miss and the one whose
        // remedy is most specific - somebody installed a certificate belonging to another site.
        if ($site->certificate_hostname_matches === false) {
            return new RuleMatch(
                severity: Severity::HIGH,
                title: 'This site\'s TLS certificate is for a different domain',
                detail: sprintf(
                    'The certificate served at %s does not cover that name%s. Every visitor is being '
                    .'shown a browser warning before they see the site, and anything calling it over '
                    .'HTTPS is either failing or ignoring the warning - which is worse.',
                    $site->expected_domain,
                    $site->certificate_subject === null ? '' : ', it is issued to '.$site->certificate_subject,
                ),
                evidence: $this->evidence($site),
            );
        }

        if ($site->certificate_self_signed === true) {
            return new RuleMatch(
                severity: Severity::HIGH,
                title: 'This site\'s TLS certificate is self-signed',
                detail: 'The certificate was signed by itself rather than by an authority, so no '
                    .'browser will accept it without somebody clicking through a warning. This is '
                    .'usually a placeholder left behind after a server was set up, or an automatic '
                    .'certificate that never completed its first renewal.',
                evidence: $this->evidence($site),
            );
        }

        if ($site->certificate_trusted === false) {
            return new RuleMatch(
                // A rank below the other two, and the distinction is real rather than tidy: this is
                // the fault that a desktop browser routinely hides. Chrome and Safari fetch a missing
                // intermediate themselves, so the site looks fine to whoever is checking it and fails
                // on Android, on curl, and on every API client - which is the shape of bug that
                // survives for months because the person testing it cannot reproduce it.
                severity: Severity::MEDIUM,
                title: 'This site\'s TLS certificate chain is incomplete',
                detail: sprintf(
                    'The certificate itself is fine, but the chain joining it to a trusted root is '
                    .'not - the server sent %s. This almost always means the intermediate certificate '
                    .'was left out of the bundle. Desktop browsers usually fetch it themselves and '
                    .'show no warning at all, so the site can look healthy while failing on Android '
                    .'devices, on curl, and for anything calling it as an API.',
                    $site->certificate_chain_length === null
                        ? 'an incomplete chain'
                        : $site->certificate_chain_length.' certificate'.($site->certificate_chain_length === 1 ? '' : 's'),
                ),
                evidence: $this->evidence($site),
            );
        }

        return null;
    }

    /**
     * @return array<string, mixed>
     */
    private function evidence(Site $site): array
    {
        // The judgements and the names on the certificate. Nothing about the site's traffic or its
        // configuration - a finding is a conclusion, and the evidence should be the smallest thing
        // that supports it.
        return array_filter([
            'issuer' => $site->certificate_issuer,
            'subject' => $site->certificate_subject,
            'hostname_matches' => $site->certificate_hostname_matches,
            'trusted' => $site->certificate_trusted,
            'self_signed' => $site->certificate_self_signed,
            'chain_length' => $site->certificate_chain_length,
            'checked_at' => $site->certificate_checked_at?->toIso8601String(),
        ], static fn (mixed $value): bool => $value !== null);
    }
}
