<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Domain\Backup\RecoveryKeyRejectedException;
use App\Domain\Backup\RecoveryKeyService;
use App\Http\Middleware\EnsureSiteBelongsToOrganisation;
use App\Models\Membership;
use App\Models\Organisation;
use App\Models\RecoveryKey;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

/**
 * Enrolling and retiring the keys that backups are encrypted to.
 *
 * Owner-only, and every action sits behind recent authentication in the route file. The reasoning is
 * not that these are dangerous in the usual sense — no key material passes through here and nothing
 * here can read a backup — but that adding a recipient is the single most consequential thing anybody
 * can do to an organisation's backups, and a hijacked session should not be able to do it quietly.
 *
 * The one thing this controller must never grow is a "generate a key for me" action. A private key
 * produced on this server would exist in a response body, possibly in a proxy buffer, and the promise
 * that we cannot read backups would become a promise about our own discipline rather than a property
 * of the system. Keys are generated by `manager-restore keygen`, on the customer's machine.
 */
final class RecoveryKeyController
{
    public function __construct(private readonly RecoveryKeyService $keys) {}

    /**
     * Register a public key and start the proof ceremony.
     */
    public function store(Request $request, Organisation $organisation): RedirectResponse
    {
        $this->authoriseOwner();

        $validated = $request->validate([
            'public_key' => ['required', 'string', 'max:2000'],
            'label' => ['nullable', 'string', 'max:120'],
        ]);

        try {
            $key = $this->keys->submit(
                $organisation,
                $this->extractKey($validated['public_key']),
                $validated['label'] ?? null,
                $request->user(),
            );
        } catch (RecoveryKeyRejectedException $e) {
            return back()->withErrors(['public_key' => $e->getMessage()])->withInput();
        }

        return redirect()
            ->route('settings.show')
            ->with('proveKey', $key->external_id)
            ->with('status', 'That key is registered. Prove you hold the other half to activate it.');
    }

    /**
     * Accept the answer to an enrolment challenge.
     */
    public function prove(Request $request, Organisation $organisation, RecoveryKey $recoveryKey): RedirectResponse
    {
        $this->authoriseOwner();
        $this->authoriseTenant($organisation, $recoveryKey);

        $validated = $request->validate([
            'proof' => ['required', 'string', 'max:100'],
        ]);

        try {
            $key = $this->keys->prove($recoveryKey, $validated['proof'], $request->user());
        } catch (RecoveryKeyRejectedException $e) {
            return back()
                ->with('proveKey', $recoveryKey->external_id)
                ->withErrors(['proof' => $e->getMessage()]);
        }

        return redirect()
            ->route('settings.show')
            ->with('status', 'Recovery key '.$key->fingerprint.' is active. New backups will be sealed to it.');
    }

    /**
     * Issue a fresh challenge for a key whose previous one expired or was exhausted.
     */
    public function rechallenge(Request $request, Organisation $organisation, RecoveryKey $recoveryKey): RedirectResponse
    {
        $this->authoriseOwner();
        $this->authoriseTenant($organisation, $recoveryKey);

        if ($recoveryKey->isRevoked()) {
            return back()->withErrors(['proof' => 'That key has been revoked.']);
        }

        $this->keys->issueChallenge($recoveryKey);

        return redirect()
            ->route('settings.show')
            ->with('proveKey', $recoveryKey->external_id)
            ->with('status', 'Here is a new challenge.');
    }

    /**
     * Take a key out of service for future backups.
     */
    public function revoke(Request $request, Organisation $organisation, RecoveryKey $recoveryKey): RedirectResponse
    {
        $this->authoriseOwner();
        $this->authoriseTenant($organisation, $recoveryKey);

        $validated = $request->validate([
            'reason' => ['required', 'string', 'min:3', 'max:255'],

            // Only consulted when this is the last active key, and it must be typed rather than
            // checked: silently stopping every backup in an organisation is worse than the friction.
            'accept_last_key' => ['nullable', 'string'],
        ]);

        $acceptLast = isset($validated['accept_last_key'])
            && strcasecmp(trim($validated['accept_last_key']), 'STOP BACKUPS') === 0;

        try {
            $this->keys->revoke($recoveryKey, $validated['reason'], $request->user(), $acceptLast);
        } catch (RecoveryKeyRejectedException $e) {
            return back()->withErrors([
                'accept_last_key' => $e->getMessage()
                    .' To do it anyway, type STOP BACKUPS in the confirmation field.',
            ]);
        }

        return redirect()
            ->route('settings.show')
            ->with('status', 'That key will not be used for new backups. Backups already taken still open with it.');
    }

    /**
     * Pull the key out of whatever the operator pasted.
     *
     * People paste the whole armoured block from the file `manager-restore keygen` wrote, because that
     * is the file they were told to open. Refusing it and asking for "just the key part" would be a
     * refusal to read the thing we asked them to produce.
     */
    private function extractKey(string $submitted): string
    {
        $trimmed = trim($submitted);

        if (! str_contains($trimmed, '-----BEGIN')) {
            return preg_replace('~\s+~', '', $trimmed) ?? $trimmed;
        }

        $body = '';
        $inBody = false;

        foreach (preg_split('~\R~', $trimmed) ?: [] as $line) {
            if (str_starts_with(trim($line), '-----')) {
                continue;
            }

            if (! $inBody && trim($line) === '') {
                $inBody = true;

                continue;
            }

            if ($inBody) {
                $body .= trim($line);
            }
        }

        return $body === '' ? $trimmed : $body;
    }

    private function authoriseOwner(): void
    {
        abort_unless(app(Membership::class)->isOwner(), 403);
    }

    /**
     * A key belongs to the organisation the request resolved to, or it does not exist.
     *
     * 404 rather than 403, matching {@see EnsureSiteBelongsToOrganisation}: a
     * refusal that distinguishes "not yours" from "not here" is an enumeration oracle.
     */
    private function authoriseTenant(Organisation $organisation, RecoveryKey $key): void
    {
        abort_if($key->organisation_id !== $organisation->id, 404);
    }
}
